-- D1 single-threaded index coverage (stalls /api/workspaces without these).
-- Unindexed filters push avg query from ~20ms toward 100ms+ (budget 10 qps -> 2 qps).
-- Mirrors @@index additions in prisma/schema.prisma (see prisma/schema.sqlite.prisma,
-- generated by src/scripts/sync-sqlite-schema.ts).
--
--   Video  [sourceId, isBaselineSample, postedAt] (src/lib/posts.ts:67, src/lib/benchmark.ts:60 + orderBy postedAt)
--   Source [workspaceId, isSelf, sourceType]      (isSelf lookups in posts.ts, gallery.ts, sources-service.ts)
--   MediaJob [sourceId, status, kind]             (outstandingJobForSource in src/lib/jobs.ts:403-415 + sources-service lookups)
--   Hook [videoId], Idea [videoId]                (cascade deletes in sources-service.ts:388-398)
--
-- Apply with: wrangler d1 migrations apply slashloop --remote
CREATE INDEX IF NOT EXISTS "Video_sourceId_isBaselineSample_postedAt_idx" ON "Video"("sourceId", "isBaselineSample", "postedAt");
CREATE INDEX IF NOT EXISTS "Source_workspaceId_isSelf_sourceType_idx" ON "Source"("workspaceId", "isSelf", "sourceType");
CREATE INDEX IF NOT EXISTS "MediaJob_sourceId_status_kind_idx" ON "MediaJob"("sourceId", "status", "kind");
CREATE INDEX IF NOT EXISTS "Hook_videoId_idx" ON "Hook"("videoId");
CREATE INDEX IF NOT EXISTS "Idea_videoId_idx" ON "Idea"("videoId");
