-- D1 read-budget drain (measured 2026-09-16 via `wrangler d1 insights`):
-- the monthly cap checks — bandwidth.ts monthlyProxyBytes and spend-cap.ts
-- getMonthlyApifySpendCents — filter UsageLog on workspaceId + kind +
-- provider + createdAt, but only single-column indexes existed, so SQLite
-- scanned the whole table on every call: ~4.2k rows x ~650 calls/day =
-- 2.7M of the 4.1M rows read in 24h (81% of the Workers Free daily cap),
-- climbing through the month as the ledger grows. The composite index turns
-- each check into a bounded range scan (aggregate _sum, no OFFSET walk).
--
-- Mirrors the @@index addition in prisma/schema.prisma (and
-- prisma/schema.sqlite.prisma, generated by src/scripts/sync-sqlite-schema.ts).
--
-- Apply with: wrangler d1 migrations apply slashloop --remote
CREATE INDEX IF NOT EXISTS "UsageLog_workspace_kind_provider_createdAt_idx"
  ON "UsageLog"("workspaceId", "kind", "provider", "createdAt");
